module.exports = {
  supportedScopes: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'Your personal data like name, gender and birthdate.',
      email: 'Your email address.',
      address: 'Your location data as registered on ECO: postal_code, country and city.',
      eco: 'The data you entered on your ECO profile.',
  },
  supportedScopesen: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'Your personal data like name, gender and birthdate.',
      email: 'Your email address.',
      address: 'Your location data as registered on ECO: postal_code, country and city.',
      eco: 'The data you entered on your ECO profile.',
  },
  supportedScopeses: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'Sus datos personales tales como nombre, género y fecha de nacimiento.',
      email: 'Su dirección email.',
      address: 'Sus datos de domicilio registrados en ECO: código postal, país y ciudad.',
      eco: 'Los datos que introdujo en su perfil de ECO.',
  },
  supportedScopesfr: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'Vos données personnelles telles que  nom, sexe, date de naissance.',
      email: 'Votre adresse de messagerie.',
      address: 'Vos données de localisation telles que enregistrées par ECO : code postal, pays, ville.',
      eco: 'Les données saisies dans votre profil ECO.',
  },
  supportedScopesde: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'Ihr persönliche Daten sowie Geschlecht und Geburtsdatum.',
      email: 'Ihre E-Mail Adresse.',
      address: 'Ihre Standortdaten bei ECO registriert: postal_code, Land und Ort.',
      eco: 'Ihre Daten die Sie bei ECO gespeichert haben.',
  },
  supportedScopesit: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'I tuoi dati personali come nome, sesso e data di nascita.',
      email: 'Il tuo indirizzo email.',
      address: 'Il tuo indirizzo come registrato su ECO: codice postale, paese e città.',
      eco: 'I dati che hai inserito nel tuo profilo ECO.',
  },
  supportedScopespt: {
      openid: 'Informs the Authorization Server that the Client is making an OpenID Connect request.',
      profile: 'Os seus dados pessoais, como nome, género, e data de nascimento.',
      email: 'O seu endereço de e-mail.',
      address: 'Os seus dados de localização registados no ECO: código postal, país e cidade.',
      eco: 'Os dados que introduziu no seu perfil ECO.',
  },


  accesCodeTTL: 60, // 60 sec
  port: 4010,

  mongoPort: 27017,
  mongoHost:'localhost',
  mongooseIDPDB: '',
  mongoIDPDBUser: '',
  mongoIDPDBPassword: '',
  mongoPort: 27017,
  mongoIDPConnection:null,
  SessionCookieName: '',
  id_tokenIssuerIdentifier: '',
  accountActivationUrl: 'idp_url/activate',
  idpMailFrom :'',
  environment:'DEV',
  versionInfo: '1.3.0',
  IDPSessionLengthDays:7,
  SessionSecret:'secret',
  RedisDbIndex:0,
  defaultRegistrationCancelUrl: 'portal_url',
  defaultRegistrationLoginUrl: 'portal_url?startup=login',
  defaultRegistrationInitiator: 'EcoPortal',
  EcoBackendEndPoint: 'backend_url',
  sendXapiStatements:false,
  sendgridUsername:'sendgridUsername',
  sendgridPassword:'sendgridPassword',
};

